"""English key -> locale translations. Glossary words stay English."""

def rows():
    # locale order: es fr it pt-BR de ko zh-Hans zh-Hant ja
    def L(es, fr, it, pt, de, ko, zhs, zht, ja):
        return {
            "es": es, "fr": fr, "it": it, "pt-BR": pt, "de": de,
            "ko": ko, "zh-Hans": zhs, "zh-Hant": zht, "ja": ja,
        }

    t = {}
    def a(en, *vals):
        t[en] = L(*vals)

    a("Connect", "Conectar", "Connexion", "Connetti", "Conectar", "Verbinden", "연결", "连接", "連接", "接続")
    a("Wake", "Activar", "Réveiller", "Riattiva", "Ligar", "Aufwecken", "켜기", "唤醒", "喚醒", "起動")
    a("Wake sent", "Señal enviada", "Signal envoyé", "Segnale inviato", "Sinal enviado", "Signal gesendet", "신호 보냄", "已发送唤醒", "已傳送喚醒", "起動信号を送信済み")
    a("Cancel", "Cancelar", "Annuler", "Annulla", "Cancelar", "Abbrechen", "취소", "取消", "取消", "キャンセル")
    a("Done", "OK", "OK", "Fine", "OK", "Fertig", "완료", "完成", "完成", "完了")
    a("Settings", "Ajustes", "Réglages", "Impostazioni", "Ajustes", "Einstellungen", "설정", "设置", "設定", "設定")
    a("Open Settings", "Abrir ajustes", "Ouvrir les réglages", "Apri impostazioni", "Abrir ajustes", "Einstellungen öffnen", "설정 열기", "打开设置", "打開設定", "設定を開く")
    a("Hide", "Ocultar", "Masquer", "Nascondi", "Ocultar", "Ausblenden", "가리기", "隐藏", "隱藏", "隠す")
    a("Remove", "Eliminar", "Supprimer", "Rimuovi", "Remover", "Entfernen", "삭제", "移除", "移除", "削除")
    a("Playing", "En partida", "En jeu", "In gioco", "Jogando", "Wiedergabe", "플레이 중", "游戏中", "遊戲中", "プレイ中")
    a("Connecting…", "Conectando…", "Connexion…", "Connessione…", "Conectando…", "Verbinden…", "연결 중…", "正在连接…", "正在連線…", "接続中…")
    a("Connect", "Conectar", "Connexion", "Connetti", "Conectar", "Verbinden", "연결", "连接", "連接", "接続")
    a("Unlock to Connect", "Desbloquear para conectar", "Déverrouiller pour se connecter", "Sblocca per connettere", "Desbloquear para conectar", "Zum Verbinden freischalten", "연결하려면 잠금 해제", "解锁后连接", "解鎖後連接", "ロック解除して接続")
    a("Pair another", "Vincular otra", "Associer une autre", "Associa un’altra", "Vincular outra", "Weitere koppeln", "다른 기기 연결", "再配对一台", "再配對一台", "別の本体を登録")
    a("Pair a PS5", "Vincular una PS5", "Associer une PS5", "Associa una PS5", "Vincular um PS5", "PS5 koppeln", "PS5 연결", "配对 PS5", "配對 PS5", "PS5を登録")
    a("Pair your console", "Vincula tu consola", "Associez votre console", "Associa la console", "Vincule o console", "Konsole koppeln", "본체를 연결하세요", "配对主机", "配對主機", "本体を登録")
    a("Pair PS5", "Vincular PS5", "Associer la PS5", "Associa PS5", "Vincular PS5", "PS5 koppeln", "PS5 연결", "配对 PS5", "配對 PS5", "PS5を登録")
    a("Pair another PlayStation 5", "Vincular otra PlayStation 5", "Associer une autre PlayStation 5", "Associa un’altra PlayStation 5", "Vincular outro PlayStation 5", "Weitere PlayStation 5 koppeln", "다른 PlayStation 5 연결", "再配对一台 PlayStation 5", "再配對一台 PlayStation 5", "別のPlayStation 5を登録")
    a("What's New", "Novedades", "Nouveautés", "Novità", "Novidades", "Neuigkeiten", "새로운 기능", "新功能", "新功能", "新着情報")
    a("What's New in Farframe", "Novedades de Farframe", "Nouveautés de Farframe", "Novità di Farframe", "Novidades do Farframe", "Neuigkeiten in Farframe", "Farframe의 새로운 기능", "Farframe 新功能", "Farframe 新功能", "Farframeの新着情報")
    a("Hide until next update", "Ocultar hasta la próxima actualización", "Masquer jusqu’à la prochaine mise à jour", "Nascondi fino al prossimo aggiornamento", "Ocultar até a próxima atualização", "Bis zum nächsten Update ausblenden", "다음 업데이트까지 숨기기", "隐藏至下次更新", "隱藏至下次更新", "次のアップデートまで非表示")
    a("Welcome to Farframe", "Bienvenido a Farframe", "Bienvenue dans Farframe", "Benvenuto in Farframe", "Boas-vindas ao Farframe", "Willkommen bei Farframe", "Farframe에 오신 것을 환영합니다", "欢迎使用 Farframe", "歡迎使用 Farframe", "Farframeへようこそ")
    a("Off", "No", "Non", "Off", "Desligado", "Aus", "끔", "关", "關", "オフ")
    a("Low", "Bajo", "Faible", "Bassa", "Baixo", "Niedrig", "낮음", "低", "低", "弱")
    a("Medium", "Medio", "Moyen", "Media", "Médio", "Mittel", "중간", "中", "中", "中")
    a("Nearby", "Cercano", "Proche", "Vicino", "Perto", "Nah", "가깝게", "贴近", "貼近", "近")
    a("Standard", "Estándar", "Standard", "Standard", "Padrão", "Standard", "표준", "标准", "標準", "標準")
    a("Wide", "Amplio", "Large", "Ampio", "Amplo", "Breit", "넓게", "宽", "寬", "広")
    a("Ambient glow", "Resplandor ambiental", "Lueur ambiante", "Bagliore ambientale", "Brilho ambiente", "Umgebungsleuchten", "앰비언트 글로우", "环境光晕", "環境光暈", "アンビエントグロー")
    a("Ambient Glow", "Resplandor ambiental", "Lueur ambiante", "Bagliore ambientale", "Brilho ambiente", "Umgebungsleuchten", "앰비언트 글로우", "环境光晕", "環境光暈", "アンビエントグロー")
    a("Spread", "Alcance", "Étendue", "Ampiezza", "Alcance", "Ausbreitung", "범위", "范围", "範圍", "広がり")
    a("Immersive environments", "Entornos inmersivos", "Environnements immersifs", "Ambienti immersivi", "Ambientes imersivos", "Immersive Umgebungen", "몰입형 환경", "沉浸环境", "沉浸環境", "イマーシブ環境")
    a("Immersive environment", "Entorno inmersivo", "Environnement immersif", "Ambiente immersivo", "Ambiente imersivo", "Immersive Umgebung", "몰입형 환경", "沉浸环境", "沉浸環境", "イマーシブ環境")
    a("Mixed", "Mixed", "Mixed", "Mixed", "Mixed", "Mixed", "Mixed", "Mixed", "Mixed", "Mixed")
    a("Glass Arena", "Glass Arena", "Glass Arena", "Glass Arena", "Glass Arena", "Glass Arena", "Glass Arena", "Glass Arena", "Glass Arena", "Glass Arena")
    a("Exit Mixed", "Salir de Mixed", "Quitter Mixed", "Esci da Mixed", "Sair do Mixed", "Mixed verlassen", "Mixed 종료", "退出 Mixed", "離開 Mixed", "Mixedを終了")
    a("Play in Glass Arena", "Jugar en Glass Arena", "Jouer dans Glass Arena", "Gioca in Glass Arena", "Jogar no Glass Arena", "In Glass Arena spielen", "Glass Arena에서 플레이", "在 Glass Arena 中游玩", "在 Glass Arena 中遊玩", "Glass Arenaでプレイ")
    a("Light boost", "Luz en las paredes", "Lumière sur les murs", "Luce sulle pareti", "Luz nas paredes", "Licht an den Wänden", "벽면 조명", "墙面光", "牆面光", "壁面ライト")
    a("Controls", "Mandos", "Commandes", "Comandi", "Controles", "Steuerung", "조작", "控制", "控制", "操作")
    a("Screen", "Pantalla", "Écran", "Schermo", "Tela", "Bild", "화면", "画面", "畫面", "画面")
    a("Stats", "Estadísticas", "Stats", "Statistiche", "Estatísticas", "Statistik", "통계", "统计", "統計", "統計")
    a("Audio", "Audio", "Audio", "Audio", "Áudio", "Audio", "오디오", "音频", "音訊", "オーディオ")
    a("Mute", "Silenciar", "Muet", "Disattiva audio", "Silenciar", "Stummschalten", "음소거", "静音", "靜音", "ミュート")
    a("Volume", "Volumen", "Volume", "Volume", "Volume", "Lautstärke", "볼륨", "音量", "音量", "音量")
    a("Session", "Sesión", "Session", "Sessione", "Sessão", "Sitzung", "세션", "会话", "工作階段", "セッション")
    a("About", "Acerca de", "À propos", "Informazioni", "Sobre", "Info", "정보", "关于", "關於", "情報")
    a("Quality", "Calidad", "Qualité", "Qualità", "Qualidade", "Qualität", "화질", "画质", "畫質", "画質")
    a("Stream Quality", "Calidad del stream", "Qualité du flux", "Qualità dello stream", "Qualidade do stream", "Streamqualität", "스트림 화질", "串流画质", "串流畫質", "ストリーム画質")
    a("Smooth motion", "Movimiento suave", "Mouvement fluide", "Movimento fluido", "Movimento suave", "Fluide Bewegung", "부드러운 움직임", "流畅画面", "流暢畫面", "スムーズモーション")
    a("Controller", "Mando", "Manette", "Controller", "Controle", "Controller", "컨트롤러", "手柄", "手把", "コントローラー")
    a("Controller feedback", "Respuesta del mando", "Retour de la manette", "Feedback del controller", "Resposta do controle", "Controller-Feedback", "컨트롤러 피드백", "手柄反馈", "手把回饋", "コントローラーフィードバック")
    a("Video enhancement", "Mejora de vídeo", "Amélioration vidéo", "Miglioramento video", "Aprimoramento de vídeo", "Videoverbesserung", "영상 향상", "画面增强", "畫面增強", "映像エンハンス")
    a("Video Settings", "Ajustes de vídeo", "Réglages vidéo", "Impostazioni video", "Ajustes de vídeo", "Videoeinstellungen", "영상 설정", "视频设置", "影片設定", "映像設定")
    a("Restore Audio", "Restaurar audio", "Rétablir l’audio", "Ripristina audio", "Restaurar áudio", "Audio wiederherstellen", "오디오 복구", "恢复音频", "恢復音訊", "オーディオを復元")
    a("Stream Stats", "Stream Stats", "Stream Stats", "Stream Stats", "Stream Stats", "Stream Stats", "Stream Stats", "Stream Stats", "Stream Stats", "Stream Stats")
    a("Connected", "Conectado", "Connecté", "Connesso", "Conectado", "Verbunden", "연결됨", "已连接", "已連線", "接続済み")
    a("Disconnect", "Desconectar", "Déconnecter", "Disconnetti", "Desconectar", "Trennen", "연결 해제", "断开", "中斷連線", "切断")
    a("Immediately", "Al instante", "Immédiatement", "Subito", "Imediatamente", "Sofort", "즉시", "立即", "立即", "すぐに")
    a("1 minute", "1 minuto", "1 minute", "1 minuto", "1 minuto", "1 Minute", "1분", "1 分钟", "1 分鐘", "1分")
    a("2 minutes", "2 minutos", "2 minutes", "2 minuti", "2 minutos", "2 Minuten", "2분", "2 分钟", "2 分鐘", "2分")
    a("5 minutes", "5 minutos", "5 minutes", "5 minuti", "5 minutos", "5 Minuten", "5분", "5 分钟", "5 分鐘", "5分")
    a("15 minutes", "15 minutos", "15 minutes", "15 minuti", "15 minutos", "15 Minuten", "15분", "15 分钟", "15 分鐘", "15分")
    a("Never", "Nunca", "Jamais", "Mai", "Nunca", "Nie", "안 함", "从不", "永不", "しない")
    a("OK", "OK", "OK", "OK", "OK", "OK", "확인", "好", "好", "OK")
    a("Try again", "Reintentar", "Réessayer", "Riprova", "Tentar de novo", "Erneut versuchen", "다시 시도", "重试", "重試", "再試行")
    a("Connect Now", "Conectar ahora", "Se connecter maintenant", "Connetti ora", "Conectar agora", "Jetzt verbinden", "지금 연결", "立即连接", "立即連接", "今すぐ接続")
    a("Retry Secure Save", "Reintentar guardado seguro", "Réessayer l’enregistrement sécurisé", "Riprova salvataggio sicuro", "Tentar salvar de novo", "Sicheres Speichern wiederholen", "보안 저장 다시 시도", "重试安全保存", "重試安全儲存", "安全な保存を再試行")
    a("Return to Home", "Volver al inicio", "Retour à l’accueil", "Torna alla Home", "Voltar ao início", "Zurück zur Home-Ansicht", "홈으로", "返回主页", "返回主畫面", "ホームに戻る")
    a("Return to Console Home", "Volver al inicio de la consola", "Retour à l’accueil de la console", "Torna alla Home della console", "Voltar à Home do console", "Zurück zur Konsolen-Home", "본체 홈으로", "返回主机主页", "返回主機主畫面", "本体のホームに戻る")
    a("Exit Room", "Salir de la sala", "Quitter la salle", "Esci dalla stanza", "Sair da sala", "Raum verlassen", "룸 나가기", "退出房间", "離開房間", "ルームを終了")
    a("Exit immersion", "Salir de la inmersión", "Quitter l’immersion", "Esci dall’immersione", "Sair da imersão", "Immersion verlassen", "몰입 종료", "退出沉浸", "離開沉浸", "イマーシブを終了")
    a("Move Controls", "Mover controles", "Déplacer les commandes", "Sposta i comandi", "Mover controles", "Steuerung verschieben", "조작 위치 이동", "移动控制条", "移動控制列", "操作バーを移動")
    a("Customize Controls", "Personalizar controles", "Personnaliser les commandes", "Personalizza i comandi", "Personalizar controles", "Steuerung anpassen", "조작 사용자화", "自定义控制", "自訂控制", "操作をカスタマイズ")
    a("Recall Controls", "Mostrar controles", "Réafficher les commandes", "Richiamo comandi", "Mostrar controles", "Steuerung einblenden", "조작 다시 표시", "重新显示控制", "重新顯示控制", "操作を再表示")
    a("Move Screen", "Mover pantalla", "Déplacer l’écran", "Sposta schermo", "Mover tela", "Bild bewegen", "화면 이동", "移动画面", "移動畫面", "画面を移動")
    a("Keep Facing Me", "Que me mire", "Rester face à moi", "Resta rivolto verso di me", "Manter voltado para mim", "Zu mir ausrichten", "나를 향하게", "始终朝向我", "始終朝向我", "常に自分の方を向く")
    a("Reset Screen", "Restablecer pantalla", "Réinitialiser l’écran", "Reimposta schermo", "Redefinir tela", "Bild zurücksetzen", "화면 재설정", "重置画面", "重設畫面", "画面をリセット")
    a("Partial Immersion", "Inmersión parcial", "Immersion partielle", "Immersione parziale", "Imersão parcial", "Teilweise Immersion", "부분 몰입", "部分沉浸", "部分沉浸", "部分イマーシブ")
    a("Save Current Position", "Guardar posición actual", "Enregistrer la position actuelle", "Salva posizione attuale", "Salvar posição atual", "Aktuelle Position speichern", "현재 위치 저장", "保存当前位置", "儲存目前位置", "現在の位置を保存")
    a("Saved Positions", "Posiciones guardadas", "Positions enregistrées", "Posizioni salvate", "Posições salvas", "Gespeicherte Positionen", "저장된 위치", "已保存位置", "已儲存位置", "保存した位置")
    a("Light Coverage", "Cobertura de luz", "Couverture lumineuse", "Copertura della luce", "Cobertura de luz", "Lichtabdeckung", "조명 범위", "光照范围", "光照範圍", "ライト範囲")
    a("Architectural Wrap", "Envolvente arquitectónica", "Habillage architectural", "Involucro architettonico", "Envoltório arquitetônico", "Architekturwolle", "공간 래핑", "建筑环绕", "建築環繞", "アーキテクチャラップ")
    a("Pillar Glow", "Resplandor de pilares", "Lueur des piliers", "Bagliore dei pilastri", "Brilho dos pilares", "Säulenleuchten", "기둥 글로우", "柱面光晕", "柱面光暈", "ピラーグロー")
    a("View", "Vista", "Vue", "Vista", "Vista", "Ansicht", "보기", "视图", "檢視", "ビュー")
    a("Cinema 1", "Cinema 1", "Cinéma 1", "Cinema 1", "Cinema 1", "Kino 1", "시네마 1", "影院 1", "影院 1", "シネマ 1")
    a("Cinema 2", "Cinema 2", "Cinéma 2", "Cinema 2", "Cinema 2", "Kino 2", "시네마 2", "影院 2", "影院 2", "シネマ 2")
    a("Seated", "Sentado", "Assis", "Seduto", "Sentado", "Sitzend", "앉은 자세", "坐姿", "坐姿", "着席")
    a("Reclined", "Reclinado", "Allongé", "Reclinato", "Reclinado", "Zurückgelehnt", "누운 자세", "斜躺", "斜躺", "リクライニング")
    a("Ceiling", "Techo", "Plafond", "Soffitto", "Teto", "Decke", "천장", "天花板", "天花板", "天井")
    a("Primary", "Principal", "Principal", "Principale", "Principal", "Primär", "기본", "主要", "主要", "メイン")
    a("Diagnostics", "Diagnóstico", "Diagnostics", "Diagnostica", "Diagnóstico", "Diagnose", "진단", "诊断", "診斷", "診断")
    a("Console", "Consola", "Console", "Console", "Console", "Konsole", "본체", "主机", "主機", "本体")
    a("Section", "Sección", "Section", "Sezione", "Seção", "Bereich", "섹션", "分区", "分區", "セクション")
    a("Farframe Pro", "Farframe Pro", "Farframe Pro", "Farframe Pro", "Farframe Pro", "Farframe Pro", "Farframe Pro", "Farframe Pro", "Farframe Pro", "Farframe Pro")
    a("Lifetime Unlock", "Desbloqueo permanente", "Déverrouillage à vie", "Sblocco permanente", "Desbloqueio permanente", "Dauerhafte Freischaltung", "평생 잠금 해제", "永久解锁", "永久解鎖", "買い切り解除")
    a("One-time purchase", "Pago único", "Achat unique", "Acquisto unico", "Compra única", "Einmaliger Kauf", "일회성 구매", "一次性购买", "一次性購買", "買い切り")
    a("Unlock Farframe", "Desbloquear Farframe", "Déverrouiller Farframe", "Sblocca Farframe", "Desbloquear o Farframe", "Farframe freischalten", "Farframe 잠금 해제", "解锁 Farframe", "解鎖 Farframe", "Farframeをロック解除")
    a("Upgrade to PRO", "Pasar a PRO", "Passer à PRO", "Passa a PRO", "Assinar o PRO", "Auf PRO upgraden", "PRO로 업그레이드", "升级到 PRO", "升級至 PRO", "PROにアップグレード")
    a("FARFRAME PRO Active", "FARFRAME PRO activo", "FARFRAME PRO actif", "FARFRAME PRO attivo", "FARFRAME PRO ativo", "FARFRAME PRO aktiv", "FARFRAME PRO 활성", "FARFRAME PRO 已启用", "FARFRAME PRO 已啟用", "FARFRAME PRO 有効")
    a("Starting Your Trial…", "Iniciando la prueba…", "Démarrage de l’essai…", "Avvio della prova…", "Iniciando o teste…", "Testversion wird gestartet…", "체험 시작 중…", "正在开始试用…", "正在開始試用…", "トライアルを開始しています…")
    a("Play at home.", "Juega en casa.", "Jouez à la maison.", "Gioca a casa.", "Jogue em casa.", "Spiele zu Hause.", "집에서 플레이하세요.", "在家畅玩。", "在家暢玩。", "自宅でプレイ。")
    a("Pay once.", "Paga una vez.", "Payez une fois.", "Paga una volta.", "Pague uma vez.", "Zahle einmal.", "한 번만 결제.", "一次付费。", "一次付費。", "一度きりのお支払い。")
    a("Connect your controller", "Conecta tu mando", "Connectez votre manette", "Collega il controller", "Conecte o controle", "Controller verbinden", "컨트롤러를 연결하세요", "连接手柄", "連接手把", "コントローラーを接続")
    a("Your consoles", "Tus consolas", "Vos consoles", "Le tue console", "Seus consoles", "Deine Konsolen", "내 본체", "你的主机", "你的主機", "登録済みの本体")
    a("Loading saved consoles…", "Cargando consolas guardadas…", "Chargement des consoles enregistrées…", "Caricamento console salvate…", "Carregando consoles salvos…", "Gespeicherte Konsolen werden geladen…", "저장된 본체 불러오는 중…", "正在加载已保存的主机…", "正在載入已儲存的主機…", "保存済みの本体を読み込み中…")
    a("Connection Addresses…", "Direcciones de conexión…", "Adresses de connexion…", "Indirizzi di connessione…", "Endereços de conexão…", "Verbindungsadressen…", "연결 주소…", "连接地址…", "連線位址…", "接続アドレス…")
    a("Re-register", "Volver a registrar", "Réenregistrer", "Registra di nuovo", "Registrar de novo", "Neu registrieren", "다시 등록", "重新注册", "重新註冊", "再登録")
    a("Remove from Remote Play", "Quitar de Remote Play", "Retirer de Remote Play", "Rimuovi da Remote Play", "Remover do Remote Play", "Aus Remote Play entfernen", "Remote Play에서 제거", "从 Remote Play 移除", "從 Remote Play 移除", "Remote Playから削除")
    a("Create", "Create", "Create", "Create", "Create", "Create", "Create", "Create", "Create", "Create")
    a("Options", "Options", "Options", "Options", "Options", "Options", "Options", "Options", "Options", "Options")
    a("Touchpad", "Panel táctil", "Pavé tactile", "Touchpad", "Touchpad", "Touchpad", "터치패드", "触控板", "觸控板", "タッチパッド")
    a("PS", "PS", "PS", "PS", "PS", "PS", "PS", "PS", "PS", "PS")
    a("PS Home", "PS Home", "PS Home", "PS Home", "PS Home", "PS Home", "PS Home", "PS Home", "PS Home", "PS Home")
    a("No Active Session", "No hay sesión activa", "Aucune session active", "Nessuna sessione attiva", "Nenhuma sessão ativa", "Keine aktive Sitzung", "활성 세션 없음", "没有进行中的会话", "沒有進行中的工作階段", "アクティブなセッションがありません")
    a("Connecting to PS5…", "Conectando a PS5…", "Connexion à la PS5…", "Connessione alla PS5…", "Conectando ao PS5…", "Verbindung zur PS5…", "PS5에 연결 중…", "正在连接 PS5…", "正在連線 PS5…", "PS5に接続中…")
    a("Remote Play is active", "Remote Play está activo", "Remote Play est actif", "Remote Play è attivo", "O Remote Play está ativo", "Remote Play ist aktiv", "Remote Play 활성", "Remote Play 进行中", "Remote Play 進行中", "Remote Play 実行中")
    a("Couldn’t complete that action", "No se pudo completar la acción", "Impossible de terminer l’action", "Impossibile completare l’azione", "Não foi possível concluir a ação", "Aktion konnte nicht abgeschlossen werden", "작업을 완료하지 못했습니다", "无法完成该操作", "無法完成該操作", "操作を完了できませんでした")
    a("Finish console pairing", "Terminar el vínculo", "Terminer l’association", "Completa l’associazione", "Concluir o vínculo", "Kopplung abschließen", "본체 연결 마치기", "完成主机配对", "完成主機配對", "本体の登録を完了")
    a("Finish restoring console data", "Terminar la restauración", "Terminer la restauration", "Completa il ripristino", "Concluir a restauração", "Wiederherstellung abschließen", "본체 데이터 복원 마치기", "完成主机数据恢复", "完成主機資料還原", "本体データの復元を完了")
    a("Try Recovery Again", "Reintentar recuperación", "Réessayer la récupération", "Riprova il ripristino", "Tentar recuperar de novo", "Wiederherstellung erneut versuchen", "복구 다시 시도", "再次尝试恢复", "再次嘗試還原", "復元を再試行")
    a("Loading view…", "Cargando vista…", "Chargement de la vue…", "Caricamento vista…", "Carregando vista…", "Ansicht wird geladen…", "보기 불러오는 중…", "正在加载视图…", "正在載入檢視…", "ビューを読み込み中…")
    a("Third-Party Notices", "Avisos de terceros", "Mentions des tiers", "Avvisi di terze parti", "Avisos de terceiros", "Hinweise Dritter", "제3자 고지", "第三方声明", "第三方聲明", "第三者通知")
    a("Farframe source", "Código de Farframe", "Code source Farframe", "Codice sorgente Farframe", "Código-fonte do Farframe", "Farframe-Quellcode", "Farframe 소스", "Farframe 源代码", "Farframe 原始碼", "Farframeのソース")
    a("Independent product", "Producto independiente", "Produit indépendant", "Prodotto indipendente", "Produto independente", "Unabhängiges Produkt", "독립 제품", "独立产品", "獨立產品", "独立した製品")
    a("License text", "Texto de la licencia", "Texte de licence", "Testo della licenza", "Texto da licença", "Lizenztext", "라이선스 전문", "许可文本", "授權文字", "ライセンス本文")
    a("Components", "Componentes", "Composants", "Componenti", "Componentes", "Komponenten", "구성 요소", "组件", "元件", "コンポーネント")
    a("Safety", "Seguridad", "Sécurité", "Sicurezza", "Segurança", "Sicherheit", "안전", "安全", "安全", "安全")
    a("Then finish pairing", "Luego termina el vínculo", "Puis terminez l’association", "Poi completa l’associazione", "Depois conclua o vínculo", "Dann Kopplung abschließen", "그런 다음 연결을 마칩니다", "然后完成配对", "然後完成配對", "その後、登録を完了します")
    a("If you already have your Account ID", "Si ya tienes tu Account ID", "Si vous avez déjà votre Account ID", "Se hai già il tuo Account ID", "Se você já tem o Account ID", "Wenn du deine Account ID schon hast", "이미 Account ID가 있는 경우", "如果你已有 Account ID", "如果你已有 Account ID", "すでにAccount IDがある場合")
    a("How to find your Account ID", "Cómo encontrar tu Account ID", "Comment trouver votre Account ID", "Come trovare l’Account ID", "Como encontrar o Account ID", "Account ID finden", "Account ID 찾는 방법", "如何查找 Account ID", "如何尋找 Account ID", "Account IDの確認方法")
    a("Remote Play Account ID", "Account ID de Remote Play", "Account ID Remote Play", "Account ID di Remote Play", "Account ID do Remote Play", "Remote-Play-Account-ID", "Remote Play Account ID", "Remote Play Account ID", "Remote Play Account ID", "Remote Play Account ID")
    a("That Account ID is not valid.", "Ese Account ID no es válido.", "Cet Account ID n’est pas valide.", "Questo Account ID non è valido.", "Esse Account ID não é válido.", "Diese Account ID ist ungültig.", "유효하지 않은 Account ID입니다.", "该 Account ID 无效。", "該 Account ID 無效。", "このAccount IDは無効です。")
    a("Continue with PlayStation", "Continuar con PlayStation", "Continuer avec PlayStation", "Continua con PlayStation", "Continuar com PlayStation", "Mit PlayStation fortfahren", "PlayStation으로 계속", "使用 PlayStation 继续", "使用 PlayStation 繼續", "PlayStationで続ける")
    a("Opening PlayStation sign-in…", "Abriendo el inicio de sesión de PlayStation…", "Ouverture de la connexion PlayStation…", "Apertura accesso PlayStation…", "Abrindo o login da PlayStation…", "PlayStation-Anmeldung wird geöffnet…", "PlayStation 로그인 여는 중…", "正在打开 PlayStation 登录…", "正在開啟 PlayStation 登入…", "PlayStationのサインインを開いています…")
    a("Pairing securely…", "Vinculando de forma segura…", "Association sécurisée…", "Associazione sicura…", "Vinculando com segurança…", "Sichere Kopplung…", "안전하게 연결하는 중…", "正在安全配对…", "正在安全配對…", "安全に登録しています…")
    a("Saving securely…", "Guardando de forma segura…", "Enregistrement sécurisé…", "Salvataggio sicuro…", "Salvando com segurança…", "Wird sicher gespeichert…", "안전하게 저장하는 중…", "正在安全保存…", "正在安全儲存…", "安全に保存しています…")
    a("Stopping pairing safely…", "Deteniendo el vínculo con seguridad…", "Arrêt sécurisé de l’association…", "Arresto sicuro dell’associazione…", "Interrompendo o vínculo com segurança…", "Kopplung wird sicher beendet…", "연결을 안전하게 중지하는 중…", "正在安全停止配对…", "正在安全停止配對…", "登録を安全に停止しています…")
    a("Finish secure save", "Terminar el guardado seguro", "Terminer l’enregistrement sécurisé", "Completa il salvataggio sicuro", "Concluir o salvamento seguro", "Sicheres Speichern abschließen", "보안 저장 마치기", "完成安全保存", "完成安全儲存", "安全な保存を完了")
    a("1. Enter your PS5 address", "1. Introduce la dirección de tu PS5", "1. Saisissez l’adresse de votre PS5", "1. Inserisci l’indirizzo della PS5", "1. Insira o endereço do PS5", "1. PS5-Adresse eingeben", "1. PS5 주소 입력", "1. 输入 PS5 地址", "1. 輸入 PS5 位址", "1. PS5のアドレスを入力")
    a("2. PlayStation account", "2. Cuenta PlayStation", "2. Compte PlayStation", "2. Account PlayStation", "2. Conta PlayStation", "2. PlayStation-Konto", "2. PlayStation 계정", "2. PlayStation 帐户", "2. PlayStation 帳號", "2. PlayStationアカウント")
    a("3. Link Device code", "3. Código de Link Device", "3. Code Link Device", "3. Codice Link Device", "3. Código Link Device", "3. Link-Device-Code", "3. Link Device 코드", "3. Link Device 代码", "3. Link Device 代碼", "3. Link Deviceコード")
    a("Console IP address", "Dirección IP de la consola", "Adresse IP de la console", "Indirizzo IP della console", "Endereço IP do console", "IP-Adresse der Konsole", "본체 IP 주소", "主机 IP 地址", "主機 IP 位址", "本体のIPアドレス")
    a("Eight-digit Link Device code", "Código Link Device de ocho dígitos", "Code Link Device à huit chiffres", "Codice Link Device a otto cifre", "Código Link Device de oito dígitos", "Achtstelliger Link-Device-Code", "8자리 Link Device 코드", "八位 Link Device 代码", "八位 Link Device 代碼", "8桁のLink Deviceコード")
    a("Link this app to your PS5", "Vincula esta app a tu PS5", "Associez cette app à votre PS5", "Associa questa app alla PS5", "Vincule este app ao PS5", "Diese App mit deiner PS5 koppeln", "이 앱을 PS5에 연결", "将此 App 连接到你的 PS5", "將此 App 連接到你的 PS5", "このAppをPS5に登録")
    a("Play at home", "Juega en casa", "Jouez à la maison", "Gioca a casa", "Jogue em casa", "Spiele zu Hause", "집에서 플레이", "在家畅玩", "在家暢玩", "自宅でプレイ")
    a("New in 1.3", "Novedad en 1.3", "Nouveau dans 1.3", "Novità della 1.3", "Novidade na 1.3", "Neu in 1.3", "1.3의 새로운 기능", "1.3 新功能", "1.3 新功能", "1.3の新機能")
    a("Your game, in your space", "Tu juego, en tu espacio", "Votre jeu, dans votre espace", "Il tuo gioco, nel tuo spazio", "Seu jogo, no seu espaço", "Dein Spiel, in deinem Raum", "내 공간에서 내 게임", "你的游戏，在你的空间", "你的遊戲，在你的空間", "自分の空間で、自分のゲームを")
    a("Place and resize freely", "Coloca y cambia el tamaño con libertad", "Placez et redimensionnez librement", "Posiziona e ridimensiona liberamente", "Posicione e redimensione à vontade", "Frei platzieren und skalieren", "자유롭게 배치하고 크기 조절", "自由放置并缩放", "自由放置並縮放", "自由に配置・サイズ変更")
    a("Move the controls", "Mueve los controles", "Déplacez les commandes", "Sposta i comandi", "Mova os controles", "Steuerung verschieben", "조작 위치 이동", "移动控制条", "移動控制列", "操作バーを移動")
    a("Pair your controller with Vision Pro", "Vincula el mando con el Vision Pro", "Associez la manette au Vision Pro", "Associa il controller al Vision Pro", "Vincule o controle ao Vision Pro", "Controller mit Vision Pro koppeln", "Vision Pro에 컨트롤러 연결", "将手柄与 Vision Pro 配对", "將手把與 Vision Pro 配對", "Vision Proにコントローラーを接続")
    a("Ambient glow in your space", "Resplandor ambiental en tu espacio", "Lueur ambiante dans votre espace", "Bagliore ambientale nel tuo spazio", "Brilho ambiente no seu espaço", "Umgebungsleuchten in deinem Raum", "내 공간의 앰비언트 글로우", "你空间里的环境光晕", "你空間裡的環境光暈", "自分の空間のアンビエントグロー")
    a("Glass Arena controls", "Controles de Glass Arena", "Commandes Glass Arena", "Comandi Glass Arena", "Controles do Glass Arena", "Glass-Arena-Steuerung", "Glass Arena 조작", "Glass Arena 控制", "Glass Arena 控制", "Glass Arenaの操作")
    a("PlayStation Plus Streaming Is Restricted", "PlayStation Plus Streaming está restringido", "Le streaming PlayStation Plus est limité", "Lo streaming PlayStation Plus è limitato", "O streaming do PlayStation Plus está restrito", "PlayStation Plus Streaming ist eingeschränkt", "PlayStation Plus 스트리밍이 제한됨", "PlayStation Plus 串流受限", "PlayStation Plus 串流受限", "PlayStation Plusストリーミングは制限されています")
    a("Exit to PlayStation Home", "Salir a PlayStation Home", "Quitter vers PlayStation Home", "Esci su PlayStation Home", "Sair para a PlayStation Home", "Zu PlayStation Home wechseln", "PlayStation Home으로 나가기", "退出到 PlayStation Home", "退出到 PlayStation Home", "PlayStation Homeに戻る")
    a("Open Farframe", "Abrir Farframe", "Ouvrir Farframe", "Apri Farframe", "Abrir o Farframe", "Farframe öffnen", "Farframe 열기", "打开 Farframe", "開啟 Farframe", "Farframeを開く")
    a("Headset off ends session after", "Casco quitado: la sesión termina tras", "Casque retiré : fin de session après", "Visore tolto: la sessione termina dopo", "Headset off: a sessão termina após", "Sitzung endet nach Absetzen des Headsets nach", "헤드셋 벗은 뒤 세션 종료", "取下头显后结束会话", "取下頭戴裝置後結束工作階段", "ヘッドセットを外してからセッション終了")
    a("Rest PS5 when player closes", "Poner la PS5 en reposo al cerrar el reproductor", "Mettre la PS5 en repos à la fermeture", "Metti la PS5 in riposo alla chiusura", "Colocar o PS5 em repouso ao fechar", "PS5 beim Schließen in den Ruhemodus", "플레이어를 닫으면 PS5 휴식 모드", "关闭播放器时让 PS5 进入休息模式", "關閉播放器時讓 PS5 進入休息模式", "プレイヤーを閉じたらPS5をレストモードに")
    a("Screen · Cinema & Positions", "Pantalla · Cine y posiciones", "Écran · Cinéma et positions", "Schermo · Cinema e posizioni", "Tela · Cinema e posições", "Bild · Kino und Positionen", "화면 · 시네마 및 위치", "画面 · 影院与位置", "畫面 · 影院與位置", "画面 · シネマと位置")
    a("Drag to any edge of the window", "Arrastra a cualquier borde de la ventana", "Faites glisser vers n’importe quel bord", "Trascina su qualsiasi bordo della finestra", "Arraste para qualquer borda da janela", "An einen beliebigen Fensterrand ziehen", "창의 아무 가장자리로 드래그", "拖到窗口任意边缘", "拖到視窗任意邊緣", "ウィンドウの任意の端へドラッグ")
    a("Play at home.\nPay once.", "Juega en casa.\nPaga una vez.", "Jouez à la maison.\nPayez une fois.", "Gioca a casa.\nPaga una volta.", "Jogue em casa.\nPague uma vez.", "Spiele zu Hause.\nZahle einmal.", "집에서 플레이하세요.\n한 번만 결제.", "在家畅玩。\n一次付费。", "在家暢玩。\n一次付費。", "自宅でプレイ。\n一度きりのお支払い。")
    a("Stream your console on your home network.", "Transmite tu consola en tu red de casa.", "Diffusez votre console sur votre réseau local.", "Trasmetti la console sulla rete di casa.", "Transmita o console na sua rede local.", "Streame deine Konsole im Heimnetz.", "집 네트워크에서 본체를 스트리밍하세요.", "在家庭网络上串流你的主机。", "在家庭網路上串流你的主機。", "自宅のネットワークで本体をストリーミング。")
    a("Your registration stays on this device.", "El registro permanece en este dispositivo.", "L’enregistrement reste sur cet appareil.", "La registrazione resta su questo dispositivo.", "O registro fica neste dispositivo.", "Die Registrierung bleibt auf diesem Gerät.", "등록 정보는 이 기기에만 저장됩니다.", "注册信息只保存在此设备上。", "註冊資料只保存在此裝置上。", "登録情報はこのデバイスにだけ保存されます。")
    a("Link a console once, then return here to Wake or Connect.", "Vincula una consola una vez y vuelve aquí para activarla o conectar.", "Associez une console une fois, puis revenez ici pour la réveiller ou vous connecter.", "Associa una console una volta, poi torna qui per riattivarla o connetterti.", "Vincule um console uma vez e volte aqui para ligar ou conectar.", "Kople eine Konsole einmal, dann wecken oder verbinden.", "본체를 한 번 연결한 뒤, 여기서 켜거나 접속하세요.", "配对一次主机，然后回到这里唤醒或连接。", "配對一次主機，然後回到這裡喚醒或連接。", "本体を一度登録したら、ここで起動または接続します。")
    a("Ambient glow in your space, plus how to pair your controller.", "Resplandor ambiental en tu espacio y cómo vincular el mando.", "Lueur ambiante dans votre espace, et comment associer la manette.", "Bagliore ambientale nel tuo spazio e come associare il controller.", "Brilho ambiente no seu espaço e como vincular o controle.", "Umgebungsleuchten in deinem Raum und Controller koppeln.", "내 공간의 앰비언트 글로우, 그리고 컨트롤러 연결 방법.", "你空间里的环境光晕，以及如何配对手柄。", "你空間裡的環境光暈，以及如何配對手把。", "自分の空間のアンビエントグローと、コントローラーの接続方法。")
    a("Wake your console, place the screen, and play.", "Enciende la consola, coloca la pantalla y juega.", "Réveillez la console, placez l’écran et jouez.", "Riattiva la console, posiziona lo schermo e gioca.", "Ligue o console, posicione a tela e jogue.", "Wecke die Konsole, platziere das Bild und spiele.", "본체를 켜고, 화면을 놓고, 플레이하세요.", "唤醒主机，放好画面，开始玩。", "喚醒主機，放好畫面，開始玩。", "本体を起動し、画面を置いてプレイ。")
    a("1. Turn the controller off and unplug its USB cable.", "1. Apaga el mando y desconecta el USB.", "1. Éteignez la manette et débranchez l’USB.", "1. Spegni il controller e stacca l’USB.", "1. Desligue o controle e desconecte o USB.", "1. Controller ausschalten und USB trennen.", "1. 컨트롤러를 끄고 USB 케이블을 빼세요.", "1. 关闭手柄并拔掉 USB 线。", "1. 關閉手把並拔掉 USB 線。", "1. コントローラーの電源を切り、USBケーブルを外します。")
    a("2. Hold PS + Create until the light flashes.", "2. Mantén PS + Create hasta que parpadee la luz.", "2. Maintenez PS + Create jusqu’à ce que la lumière clignote.", "2. Tieni premuti PS + Create finché la luce lampeggia.", "2. Segure PS + Create até a luz piscar.", "2. PS + Create halten, bis das Licht blinkt.", "2. 표시등이 깜빡일 때까지 PS + Create를 누르세요.", "2. 按住 PS + Create 直到指示灯闪烁。", "2. 按住 PS + Create 直到指示燈閃爍。", "2. ランプが点滅するまでPS + Createを押し続けます。")
    a("Create is left of the touchpad, opposite Options.", "Create está a la izquierda del panel táctil, frente a Options.", "Create est à gauche du pavé tactile, face à Options.", "Create è a sinistra del touchpad, opposto a Options.", "Create fica à esquerda do touchpad, oposto a Options.", "Create liegt links vom Touchpad, gegenüber von Options.", "Create는 터치패드 왼쪽, Options 반대편입니다.", "Create 在触控板左侧，Options 对面。", "Create 在觸控板左側，Options 對面。", "Createはタッチパッドの左、Optionsの反対側です。")
    a("3. On Vision Pro, open Settings > Bluetooth and select your controller.", "3. En Vision Pro, abre Ajustes > Bluetooth y elige el mando.", "3. Sur Vision Pro, ouvrez Réglages > Bluetooth et choisissez la manette.", "3. Su Vision Pro, apri Impostazioni > Bluetooth e seleziona il controller.", "3. No Vision Pro, abra Ajustes > Bluetooth e selecione o controle.", "3. Auf Vision Pro Einstellungen > Bluetooth öffnen und den Controller wählen.", "3. Vision Pro에서 설정 > Bluetooth를 열고 컨트롤러를 선택하세요.", "3. 在 Vision Pro 打开设置 > Bluetooth，选择手柄。", "3. 在 Vision Pro 打開設定 > Bluetooth，選擇手把。", "3. Vision Proで設定 > Bluetoothを開き、コントローラーを選びます。")
    a("To reconnect to your PS5 later, connect it to the console with a USB cable and press PS.", "Para volver a la PS5, conéctalo a la consola con USB y pulsa PS.", "Pour la reconnecter à la PS5, branchez-la en USB sur la console et appuyez sur PS.", "Per ricollegarlo alla PS5, collegalo alla console con USB e premi PS.", "Para reconectar ao PS5, ligue-o ao console com USB e pressione PS.", "Später an die PS5: per USB an die Konsole und PS drücken.", "나중에 PS5에 다시 쓰려면 USB로 본체에 연결한 뒤 PS를 누르세요.", "之后若要连回 PS5，用 USB 接到主机并按 PS。", "之後若要連回 PS5，用 USB 接到主機並按 PS。", "あとでPS5に戻すには、USBで本体に接続してPSを押します。")
    a("Keep your PS5 and Vision Pro on the same network during pairing.", "Mantén la PS5 y el Vision Pro en la misma red al vincular.", "Gardez la PS5 et le Vision Pro sur le même réseau pendant l’association.", "Tieni PS5 e Vision Pro sulla stessa rete durante l’associazione.", "Mantenha o PS5 e o Vision Pro na mesma rede ao vincular.", "PS5 und Vision Pro beim Koppeln im selben Netz lassen.", "연결하는 동안 PS5와 Vision Pro를 같은 네트워크에 두세요.", "配对时请让 PS5 和 Vision Pro 在同一网络。", "配對時請讓 PS5 和 Vision Pro 在同一網路。", "登録中はPS5とVision Proを同じネットワークにしてください。")
    a("Nearby hugs the picture. Standard is a fuller ring. Wide is the broad wash.", "Nearby abraza la imagen. Standard es un anillo más completo. Wide es el lavado amplio.", "Nearby colle l’image. Standard est un anneau plus plein. Wide est le halo large.", "Nearby abbraccia l’immagine. Standard è un anello più pieno. Wide è il bagliore ampio.", "Nearby cola na imagem. Standard é um anel mais cheio. Wide é o brilho amplo.", "Nearby sitzt eng am Bild. Standard ist ein vollerer Ring. Wide ist die breite Wäsche.", "Nearby는 화면에 밀착됩니다. Standard는 더 풍부한 링입니다. Wide는 넓은 빛입니다.", "Nearby 贴紧画面。Standard 是更完整的光环。Wide 是大范围光晕。", "Nearby 貼緊畫面。Standard 是更完整的光環。Wide 是大範圍光暈。", "Nearbyは画面に密着。Standardはより豊かなリング。Wideは広いウォッシュです。")
    a("Glow around the window in your space. Nearby, Standard, and Wide change how far it reaches.", "Resplandor alrededor de la ventana en tu espacio. Nearby, Standard y Wide cambian el alcance.", "Lueur autour de la fenêtre dans votre espace. Nearby, Standard et Wide changent la portée.", "Bagliore intorno alla finestra nel tuo spazio. Nearby, Standard e Wide cambiano la portata.", "Brilho ao redor da janela no seu espaço. Nearby, Standard e Wide mudam o alcance.", "Leuchten um das Fenster in deinem Raum. Nearby, Standard und Wide ändern die Reichweite.", "공간 속 창 둘레의 글로우입니다. Nearby, Standard, Wide가 범위를 바꿉니다.", "窗口周围的光晕。Nearby、Standard 和 Wide 改变范围。", "視窗周圍的光暈。Nearby、Standard 和 Wide 改變範圍。", "空間のウィンドウ周りに光ります。Nearby、Standard、Wideで広さが変わります。")
    a("100% is screen glow only. Raise this for light on the walls.", "El 100 % es solo el resplandor de la pantalla. Súbelo para luz en las paredes.", "100 % = lueur d’écran seulement. Augmentez pour éclairer les murs.", "Il 100% è solo il bagliore dello schermo. Alza per la luce sulle pareti.", "100% é só o brilho da tela. Aumente para luz nas paredes.", "100 % ist nur Bildleuchten. Höher = Licht an den Wänden.", "100%는 화면 글로우만입니다. 올리면 벽에 빛이 퍼집니다.", "100% 仅为屏幕光晕。调高可照亮墙壁。", "100% 僅為螢幕光暈。調高可照亮牆壁。", "100%は画面のグローのみ。上げると壁も照らします。")
    a("A full mixed environment, with optional light on the walls.", "Un entorno Mixed completo, con luz opcional en las paredes.", "Un environnement Mixed complet, avec lumière optionnelle sur les murs.", "Un ambiente Mixed completo, con luce opzionale sulle pareti.", "Um ambiente Mixed completo, com luz opcional nas paredes.", "Eine volle Mixed-Umgebung, optional mit Licht an den Wänden.", "벽면 조명을 선택할 수 있는 완전한 Mixed 환경.", "完整 Mixed 环境，可选择墙面光。", "完整 Mixed 環境，可選擇牆面光。", "壁面ライトも選べる、完全なMixed環境です。")
    a("Exit Mixed to choose Glass Arena.", "Sal de Mixed para elegir Glass Arena.", "Quittez Mixed pour choisir Glass Arena.", "Esci da Mixed per scegliere Glass Arena.", "Saia do Mixed para escolher o Glass Arena.", "Mixed verlassen, um Glass Arena zu wählen.", "Glass Arena를 쓰려면 Mixed를 종료하세요.", "退出 Mixed 以选择 Glass Arena。", "離開 Mixed 以選擇 Glass Arena。", "Glass Arenaを選ぶにはMixedを終了します。")
    a("Mixed wall light requires visionOS 27.", "La luz de pared Mixed requiere visionOS 27.", "La lumière murale Mixed nécessite visionOS 27.", "La luce a parete Mixed richiede visionOS 27.", "A luz de parede Mixed exige visionOS 27.", "Mixed-Wandlicht braucht visionOS 27.", "Mixed 벽면 조명은 visionOS 27이 필요합니다.", "Mixed 墙面光需要 visionOS 27。", "Mixed 牆面光需要 visionOS 27。", "Mixedの壁面ライトにはvisionOS 27が必要です。")
    a("Choose a saved console from Farframe.", "Elige una consola guardada en Farframe.", "Choisissez une console enregistrée dans Farframe.", "Scegli una console salvata in Farframe.", "Escolha um console salvo no Farframe.", "Wähle eine gespeicherte Konsole in Farframe.", "Farframe에서 저장된 본체를 선택하세요.", "从 Farframe 选择已保存的主机。", "從 Farframe 選擇已儲存的主機。", "Farframeで保存済みの本体を選んでください。")
    a("Exit Room returns your game to this window.", "Salir de la sala devuelve el juego a esta ventana.", "Quitter la salle ramène le jeu dans cette fenêtre.", "Esci dalla stanza riporta il gioco in questa finestra.", "Sair da sala devolve o jogo a esta janela.", "Raum verlassen legt das Spiel in dieses Fenster zurück.", "룸을 나가면 게임이 이 창으로 돌아옵니다.", "退出房间后游戏回到此窗口。", "離開房間後遊戲回到此視窗。", "ルームを終了するとゲームはこのウィンドウに戻ります。")
    a("Returns to your window without disconnecting.", "Vuelve a tu ventana sin desconectar.", "Revient à votre fenêtre sans déconnecter.", "Torna alla finestra senza disconnettere.", "Volta à janela sem desconectar.", "Zurück zum Fenster, ohne zu trennen.", "연결을 끊지 않고 창으로 돌아갑니다.", "不断开连接，回到窗口。", "不斷開連線，回到視窗。", "切断せずにウィンドウへ戻ります。")
    a("Quality changes apply on the next connection.", "Los cambios de calidad se aplican en la próxima conexión.", "Les changements de qualité s’appliquent à la prochaine connexion.", "Le modifiche alla qualità valgono alla prossima connessione.", "As mudanças de qualidade valem na próxima conexão.", "Qualitätsänderungen gelten bei der nächsten Verbindung.", "화질 변경은 다음 연결부터 적용됩니다.", "画质更改将在下次连接时生效。", "畫質變更將在下次連線時生效。", "画質の変更は次の接続から適用されます。")
    a("Copies stream health without account or network identifiers.", "Copia el estado del stream sin identificadores de cuenta ni de red.", "Copie l’état du flux sans identifiants de compte ni de réseau.", "Copia lo stato dello stream senza identificatori di account o rete.", "Copia a saúde do stream sem identificadores de conta ou rede.", "Kopiert den Streamzustand ohne Konto- oder Netzkennungen.", "계정·네트워크 식별자 없이 스트림 상태를 복사합니다.", "复制串流健康信息，不含帐户或网络标识。", "複製串流健康資訊，不含帳號或網路識別。", "アカウントやネットワーク識別子なしでストリーム状態をコピーします。")
    a("Restart sound without disconnecting your game. Keeps your volume and mute settings.", "Reinicia el audio sin desconectar la partida. Conserva volumen y silencio.", "Relance le son sans déconnecter. Conserve volume et sourdine.", "Riavvia l’audio senza disconnettere. Mantiene volume e muto.", "Reinicia o áudio sem desconectar. Mantém volume e mudo.", "Startet den Ton neu, ohne zu trennen. Lautstärke und Stummschaltung bleiben.", "게임을 끊지 않고 소리를 다시 시작합니다. 볼륨과 음소거를 유지합니다.", "不断开游戏即可重启声音。保留音量和静音。", "不斷開遊戲即可重啟聲音。保留音量和靜音。", "切断せずに音声を再開します。音量とミュートはそのままです。")
    a("Tap to mute or unmute. Drag left or right to adjust volume.", "Toca para silenciar. Arrastra para el volumen.", "Touchez pour couper le son. Faites glisser pour le volume.", "Tocca per disattivare l’audio. Trascina per il volume.", "Toque para silenciar. Arraste para o volume.", "Tippen zum Stummschalten. Ziehen für die Lautstärke.", "탭하면 음소거, 좌우로 드래그하면 볼륨입니다.", "点按静音。左右拖动调节音量。", "點按靜音。左右拖動調節音量。", "タップでミュート。左右にドラッグで音量。")
    a("Volume. Drag to 0% to mute.", "Volumen. Arrastra a 0 % para silenciar.", "Volume. Glissez à 0 % pour couper.", "Volume. Trascina a 0% per disattivare.", "Volume. Arraste a 0% para silenciar.", "Lautstärke. Auf 0 % ziehen zum Stummschalten.", "볼륨. 0%로 드래그하면 음소거입니다.", "音量。拖到 0% 即静音。", "音量。拖到 0% 即靜音。", "音量。0%までドラッグするとミュート。")
    a("Off disconnects Remote Play and leaves the console awake.", "Off desconecta Remote Play y deja la consola encendida.", "Off déconnecte Remote Play et laisse la console allumée.", "Off disconnette Remote Play e lascia la console accesa.", "Off desconecta o Remote Play e deixa o console ligado.", "Aus trennt Remote Play und lässt die Konsole an.", "끄면 Remote Play만 끊고 본체는 켜 둡니다.", "关则断开 Remote Play，主机保持开机。", "關則中斷 Remote Play，主機保持開機。", "オフにするとRemote Playだけ切断し、本体は起動したままです。")
    a("Reactive lighting is off with Reduce Motion.", "La luz reactiva se apaga con Reducir movimiento.", "L’éclairage réactif est désactivé avec Réduire les animations.", "La luce reattiva è disattivata con Riduci movimento.", "A iluminação reativa desliga com Reduzir movimento.", "Reaktives Licht ist bei Bewegungen reduzieren aus.", "동작 줄이기가 켜져 있으면 반응 조명이 꺼집니다.", "减弱动态时关闭反应光照。", "減弱動態時關閉反應光照。", "モーションを減らすと反応ライトはオフです。")
    a("Architectural Wrap is unavailable. Screen lighting still works.", "Architectural Wrap no está disponible. La luz de pantalla sigue funcionando.", "Architectural Wrap est indisponible. L’éclairage d’écran fonctionne encore.", "Architectural Wrap non è disponibile. La luce dello schermo funziona.", "Architectural Wrap indisponível. A luz da tela ainda funciona.", "Architectural Wrap ist nicht verfügbar. Bildlicht funktioniert weiter.", "Architectural Wrap을 쓸 수 없습니다. 화면 조명은 동작합니다.", "无法使用 Architectural Wrap。屏幕光照仍可用。", "無法使用 Architectural Wrap。螢幕光照仍可用。", "Architectural Wrapは使えません。画面ライトは動作します。")
    a("Changes the scenery while keeping your screen and game in place.", "Cambia el paisaje y deja pantalla y juego en su sitio.", "Change le décor sans bouger l’écran ni le jeu.", "Cambia lo sfondo e lascia schermo e gioco al loro posto.", "Muda o cenário e mantém tela e jogo no lugar.", "Wechselt die Szenerie, Bild und Spiel bleiben.", "화면과 게임은 그대로 두고 배경만 바꿉니다.", "只换风景，画面和游戏不动。", "只換風景，畫面和遊戲不動。", "画面とゲームはそのまま、景色だけ変えます。")
    a("Turn the Digital Crown to adjust your surroundings.", "Gira la Digital Crown para ajustar el entorno.", "Tournez la Digital Crown pour ajuster l’environnement.", "Gira la Digital Crown per regolare l’ambiente.", "Gire a Digital Crown para ajustar o entorno.", "Digital Crown drehen, um die Umgebung anzupassen.", "Digital Crown을 돌려 주변을 조절하세요.", "转动 Digital Crown 调节周围环境。", "轉動 Digital Crown 調節周圍環境。", "Digital Crownを回して周囲を調整します。")
    a("Each one sets the quality and smooth motion below. You can still change either by hand.", "Cada uno fija la calidad y el movimiento suave. Aún puedes cambiarlos a mano.", "Chacun règle qualité et mouvement fluide. Vous pouvez encore les changer à la main.", "Ognuno imposta qualità e movimento fluido. Puoi ancora cambiarli a mano.", "Cada um define qualidade e movimento suave. Você ainda pode mudar na mão.", "Jedes setzt Qualität und fluide Bewegung. Beides bleibt manuell änderbar.", "각각 아래의 화질과 부드러운 움직임을 설정합니다. 직접 바꿀 수도 있습니다.", "每一项会设定下面的画质和流畅画面。仍可手动更改。", "每一項會設定下面的畫質和流暢畫面。仍可手動更改。", "それぞれ下の画質とスムーズモーションを設定します。手動でも変えられます。")
    a("DualSense labels use their standard PS5 mapping: right Options, left Create.", "Las etiquetas DualSense siguen el mapeo PS5: Options a la derecha, Create a la izquierda.", "Les libellés DualSense suivent le mapping PS5 : Options à droite, Create à gauche.", "Le etichette DualSense seguono il mapping PS5: Options a destra, Create a sinistra.", "Os rótulos DualSense seguem o mapeamento PS5: Options à direita, Create à esquerda.", "DualSense-Beschriftung wie auf der PS5: Options rechts, Create links.", "DualSense 라벨은 표준 PS5 배치입니다. 오른쪽 Options, 왼쪽 Create.", "DualSense 标注按 PS5 标准：右 Options，左 Create。", "DualSense 標註依 PS5 標準：右 Options，左 Create。", "DualSenseの表示はPS5と同じ配置です。右がOptions、左がCreate。")
    a("On PS5, open Settings > Network > Connection Status to find its local IP address.", "En PS5, Ajustes > Red > Estado de la conexión para ver la IP local.", "Sur PS5, Réglages > Réseau > État de la connexion pour l’IP locale.", "Su PS5, Impostazioni > Rete > Stato della connessione per l’IP locale.", "No PS5, Ajustes > Rede > Status da conexão para ver o IP local.", "Auf der PS5: Einstellungen > Netzwerk > Verbindungsstatus für die lokale IP.", "PS5에서 설정 > 네트워크 > 연결 상태로 로컬 IP를 확인하세요.", "在 PS5 打开设置 > 网络 > 连接状态以查看本地 IP。", "在 PS5 打開設定 > 網路 > 連線狀態以查看本機 IP。", "PS5で設定 > ネットワーク > 接続状況を開き、ローカルIPを確認します。")
    a("On PS5, open Settings > System > Remote Play > Link Device and leave the code visible.", "En PS5, Ajustes > Sistema > Remote Play > Link Device y deja el código visible.", "Sur PS5, Réglages > Système > Remote Play > Link Device et laissez le code visible.", "Su PS5, Impostazioni > Sistema > Remote Play > Link Device e lascia il codice visibile.", "No PS5, Ajustes > Sistema > Remote Play > Link Device e deixe o código visível.", "Auf der PS5: Einstellungen > System > Remote Play > Link Device, Code sichtbar lassen.", "PS5에서 설정 > 시스템 > Remote Play > Link Device를 열고 코드를 보이게 두세요.", "在 PS5 打开设置 > 系统 > Remote Play > Link Device，并保持代码可见。", "在 PS5 打開設定 > 系統 > Remote Play > Link Device，並保持代碼可見。", "PS5で設定 > システム > Remote Play > Link Deviceを開き、コードを表示したままにします。")
    a("Do not request another Link Device code. Retry the secure save below.", "No pidas otro código Link Device. Reintenta el guardado seguro abajo.", "Ne demandez pas un autre code Link Device. Réessayez l’enregistrement sécurisé ci-dessous.", "Non richiedere un altro codice Link Device. Riprova il salvataggio sicuro sotto.", "Não peça outro código Link Device. Tente o salvamento seguro abaixo.", "Keinen neuen Link-Device-Code anfordern. Sicheres Speichern unten erneut versuchen.", "Link Device 코드를 다시 받지 마세요. 아래 보안 저장을 다시 시도하세요.", "不要再申请 Link Device 代码。请重试下面的安全保存。", "不要再申請 Link Device 代碼。請重試下面的安全儲存。", "新しいLink Deviceコードは発行しないでください。下の安全な保存を再試行します。")
    a("The PS5 is already paired. Verifying its registration on this device.", "La PS5 ya está vinculada. Se verifica el registro en este dispositivo.", "La PS5 est déjà associée. Vérification de l’enregistrement sur cet appareil.", "La PS5 è già associata. Verifica della registrazione su questo dispositivo.", "O PS5 já está vinculado. Verificando o registro neste dispositivo.", "Die PS5 ist schon gekoppelt. Registrierung auf diesem Gerät wird geprüft.", "PS5는 이미 연결되어 있습니다. 이 기기의 등록을 확인합니다.", "PS5 已配对。正在验证此设备上的注册。", "PS5 已配對。正在驗證此裝置上的註冊。", "PS5はすでに登録済みです。このデバイスの登録を確認しています。")
    a("Contacting the PS5, exchanging registration, and saving it to this device.", "Contactando la PS5, intercambiando el registro y guardándolo aquí.", "Contact de la PS5, échange d’enregistrement, sauvegarde sur cet appareil.", "Contatto con la PS5, scambio della registrazione e salvataggio qui.", "Falando com o PS5, trocando o registro e salvando neste dispositivo.", "PS5 wird kontaktiert, Registrierung getauscht und hier gespeichert.", "PS5에 연결해 등록을 교환하고 이 기기에 저장합니다.", "正在联系 PS5、交换注册并保存到此设备。", "正在聯絡 PS5、交換註冊並儲存到此裝置。", "PS5に接続し、登録を交換してこのデバイスに保存します。")
    a("This removes the saved registration from this app. It does not put the PS5 in Rest Mode or revoke other Remote Play devices.", "Quita el registro guardado de esta app. No pone la PS5 en reposo ni revoca otros dispositivos Remote Play.", "Retire l’enregistrement de cette app. Ne met pas la PS5 en repos et ne révoque pas les autres appareils Remote Play.", "Rimuove la registrazione da questa app. Non mette la PS5 in riposo e non revoca altri dispositivi Remote Play.", "Remove o registro deste app. Não coloca o PS5 em repouso nem revoga outros dispositivos Remote Play.", "Entfernt die Registrierung aus dieser App. Die PS5 geht nicht in den Ruhemodus, andere Remote-Play-Geräte bleiben.", "이 앱에서 저장된 등록만 삭제합니다. PS5를 휴식 모드로 넣거나 다른 Remote Play 기기를 취소하지 않습니다.", "仅从此 App 删除已保存的注册。不会让 PS5 进入休息模式，也不会撤销其他 Remote Play 设备。", "僅從此 App 刪除已儲存的註冊。不會讓 PS5 進入休息模式，也不會撤銷其他 Remote Play 裝置。", "このAppから保存済み登録だけを削除します。PS5をレストモードにはせず、他のRemote Play機器も取り消しません。")
    a("Remote Play will not change pairing data until recovery completes.", "Remote Play no cambiará los datos de vínculo hasta terminar la recuperación.", "Remote Play ne modifiera pas les données d’association tant que la récupération n’est pas terminée.", "Remote Play non cambia i dati di associazione finché il ripristino non è completo.", "O Remote Play não altera os dados de vínculo até a recuperação terminar.", "Remote Play ändert Kopplungsdaten erst, wenn die Wiederherstellung fertig ist.", "복구가 끝날 때까지 Remote Play는 연결 데이터를 바꾸지 않습니다.", "恢复完成前，Remote Play 不会更改配对数据。", "還原完成前，Remote Play 不會更改配對資料。", "復元が終わるまで、Remote Playは登録データを変更しません。")
    a("The registration was verified and saved securely. You will not need this Link Device code again.", "El registro se verificó y guardó con seguridad. No volverás a necesitar este código Link Device.", "L’enregistrement a été vérifié et sauvé. Vous n’aurez plus besoin de ce code Link Device.", "La registrazione è verificata e salvata. Non ti servirà più questo codice Link Device.", "O registro foi verificado e salvo. Você não precisará mais deste código Link Device.", "Registrierung geprüft und sicher gespeichert. Diesen Link-Device-Code brauchst du nicht mehr.", "등록이 확인되어 안전하게 저장되었습니다. 이 Link Device 코드는 다시 필요 없습니다.", "注册已验证并安全保存。你不再需要此 Link Device 代码。", "註冊已驗證並安全儲存。你不再需要此 Link Device 代碼。", "登録は確認され、安全に保存されました。このLink Deviceコードはもう使いません。")
    a("Review the message, correct any details, and try again. Request a fresh Link Device code if the previous code expired or was rejected.", "Revisa el mensaje, corrige los datos y reintenta. Pide un código Link Device nuevo si el anterior caducó o se rechazó.", "Relisez le message, corrigez, réessayez. Demandez un nouveau code Link Device si l’ancien a expiré ou a été refusé.", "Rileggi il messaggio, correggi e riprova. Richiedi un nuovo codice Link Device se il precedente è scaduto o rifiutato.", "Revise a mensagem, corrija e tente de novo. Peça um código Link Device novo se o anterior expirou ou foi recusado.", "Meldung prüfen, korrigieren, erneut versuchen. Neuen Link-Device-Code holen, wenn der alte abgelaufen oder abgelehnt wurde.", "메시지를 확인하고 수정한 뒤 다시 시도하세요. 이전 코드가 만료되거나 거절되면 새 Link Device 코드를 받으세요.", "查看提示、更正后重试。若上一份代码过期或被拒绝，请申请新的 Link Device 代码。", "查看提示、更正後重試。若上一份代碼過期或被拒絕，請申請新的 Link Device 代碼。", "メッセージを確認して直し、再試行してください。前のコードが期限切れまたは拒否されたら、新しいLink Deviceコードを発行します。")
    a("This identifier is used only for the local PS5 registration attempt and is cleared from the form afterward. Never enter your PlayStation password here.", "Este identificador solo se usa para el registro local de la PS5 y luego se borra del formulario. Nunca pongas aquí tu contraseña de PlayStation.", "Cet identifiant sert uniquement à l’enregistrement local de la PS5, puis est effacé. N’entrez jamais votre mot de passe PlayStation ici.", "Questo identificatore serve solo al tentativo di registrazione locale della PS5 e poi viene cancellato. Non inserire mai qui la password PlayStation.", "Este identificador serve só para o registro local do PS5 e depois é apagado. Nunca coloque a senha da PlayStation aqui.", "Diese Kennung gilt nur für die lokale PS5-Registrierung und wird danach gelöscht. Niemals das PlayStation-Passwort hier eingeben.", "이 식별자는 로컬 PS5 등록 시도에만 쓰이며 이후 양식에서 지워집니다. PlayStation 비밀번호는 여기에 넣지 마세요.", "此标识仅用于本次本地 PS5 注册，之后会从表单清除。切勿在此输入 PlayStation 密码。", "此識別僅用於本次本機 PS5 註冊，之後會从表單清除。切勿在此輸入 PlayStation 密碼。", "この識別子は今回のローカルPS5登録にだけ使い、その後フォームから消します。PlayStationのパスワードはここに入れないでください。")
    a("Wake your console on your home network, connect, and put the screen where it feels comfortable.", "Enciende la consola en tu red de casa, conecta y coloca la pantalla donde te resulte cómodo.", "Réveillez la console sur le réseau local, connectez-vous et placez l’écran où c’est confortable.", "Riattiva la console sulla rete di casa, connetti e metti lo schermo dove sta comodo.", "Ligue o console na rede de casa, conecte e coloque a tela onde for confortável.", "Wecke die Konsole im Heimnetz, verbinde, und setze das Bild, wo es sich gut anfühlt.", "집 네트워크에서 본체를 켜고 연결한 뒤, 편한 곳에 화면을 두세요.", "在家庭网络上唤醒主机、连接，并把画面放到舒服的位置。", "在家庭網路上喚醒主機、連接，並把畫面放到舒服的位置。", "自宅ネットワークで本体を起動して接続し、画面を楽な位置に置きます。")
    a("Move the window and make the picture as large or as small as you want.", "Mueve la ventana y haz la imagen tan grande o pequeña como quieras.", "Déplacez la fenêtre et donnez à l’image la taille que vous voulez.", "Sposta la finestra e rendi l’immagine grande o piccola a piacere.", "Mova a janela e deixe a imagem do tamanho que quiser.", "Verschiebe das Fenster und mache das Bild so groß oder klein, wie du willst.", "창을 옮기고 화면을 원하는 크기로 조절하세요.", "移动窗口，把画面放到你想要的大小。", "移動視窗，把畫面放到你想要的大小。", "ウィンドウを動かし、画面は好きな大きさに。")
    a("Drag the control rail to any side of the game.", "Arrastra la barra de controles a cualquier lado del juego.", "Faites glisser la barre de commandes sur n’importe quel côté du jeu.", "Trascina la barra dei comandi su qualsiasi lato del gioco.", "Arraste a barra de controles para qualquer lado do jogo.", "Ziehe die Steuerleiste an jede Seite des Spiels.", "조작 막대를 게임 화면의 어느 쪽으로든 드래그하세요.", "把控制条拖到游戏画面的任意一侧。", "把控制列拖到遊戲畫面的任意一側。", "操作バーをゲームの好きな辺へドラッグします。")
    a("Turn the controller off, hold PS and Create until the light flashes, then choose it in Settings, Bluetooth. Pair it with Vision Pro, not the console.", "Apaga el mando, mantén PS y Create hasta que parpadee, y elígelo en Ajustes, Bluetooth. Vínculalo con Vision Pro, no con la consola.", "Éteignez la manette, maintenez PS et Create jusqu’au clignotement, puis choisissez-la dans Réglages, Bluetooth. Associez-la au Vision Pro, pas à la console.", "Spegni il controller, tieni PS e Create finché lampeggia, poi sceglilo in Impostazioni, Bluetooth. Associalo al Vision Pro, non alla console.", "Desligue o controle, segure PS e Create até piscar e escolha em Ajustes, Bluetooth. Vincule ao Vision Pro, não ao console.", "Controller aus, PS und Create halten bis es blinkt, dann in Einstellungen, Bluetooth wählen. Mit Vision Pro koppeln, nicht mit der Konsole.", "컨트롤러를 끄고, 표시등이 깜빡일 때까지 PS와 Create를 누른 뒤 설정, Bluetooth에서 선택하세요. 본체가 아니라 Vision Pro에 연결합니다.", "关闭手柄，按住 PS 和 Create 直到闪灯，然后在设置、Bluetooth 中选择。请配对到 Vision Pro，而不是主机。", "關閉手把，按住 PS 和 Create 直到閃燈，然後在設定、Bluetooth 中選擇。請配對到 Vision Pro，而不是主機。", "コントローラーを切り、点滅するまでPSとCreateを押し、設定、Bluetoothで選びます。本体ではなくVision Proに接続してください。")
    a("Color from the game around the window while you stay in shared space. This is the highlight of 1.3.", "Color del juego alrededor de la ventana, en el espacio compartido. Es lo más destacado de 1.3.", "La couleur du jeu autour de la fenêtre, dans l’espace partagé. C’est le point fort de 1.3.", "Il colore del gioco intorno alla finestra, nello spazio condiviso. È il punto forte della 1.3.", "A cor do jogo ao redor da janela, no espaço compartilhado. É o destaque da 1.3.", "Spielfarbe um das Fenster, im gemeinsamen Raum. Das Highlight von 1.3.", "공유 공간에 머문 채 창 둘레에 게임 색이 퍼집니다. 1.3의 핵심입니다.", "留在共享空间，窗口周围带上游戏的颜色。这是 1.3 的亮点。", "留在共享空間，視窗周圍帶上遊戲的顏色。這是 1.3 的亮點。", "共有空間のまま、ウィンドウ周りにゲームの色がにじみます。1.3の見どころです。")
    a("Ambient glow in shared space, plus immersive rooms when you want them.", "Resplandor ambiental en el espacio compartido y salas inmersivas cuando las quieras.", "Lueur ambiante dans l’espace partagé, plus des salles immersives quand vous voulez.", "Bagliore ambientale nello spazio condiviso e stanze immersive quando vuoi.", "Brilho ambiente no espaço compartilhado e salas imersivas quando quiser.", "Umgebungsleuchten im gemeinsamen Raum, plus immersive Räume wenn du willst.", "공유 공간의 앰비언트 글로우, 원할 땐 몰입형 룸.", "共享空间里的环境光晕，需要时再进入沉浸房间。", "共享空間裡的環境光暈，需要時再進入沉浸房間。", "共有空間のアンビエントグロー。必要ならイマーシブルームも。")
    a("Mixed and Glass Arena add immersive glow and room options around your game when you want a full environment.", "Mixed y Glass Arena añaden resplandor inmersivo y opciones de sala cuando quieres un entorno completo.", "Mixed et Glass Arena ajoutent lueur immersive et options de salle pour un environnement complet.", "Mixed e Glass Arena aggiungono bagliore immersivo e opzioni di stanza per un ambiente completo.", "Mixed e Glass Arena acrescentam brilho imersivo e opções de sala quando você quer um ambiente completo.", "Mixed und Glass Arena ergänzen immersives Leuchten und Raumoptionen, wenn du eine volle Umgebung willst.", "완전한 환경이 필요할 때 Mixed와 Glass Arena가 몰입형 글로우와 룸 옵션을 더합니다.", "需要完整体验时，Mixed 和 Glass Arena 为游戏加上沉浸光晕和房间选项。", "需要完整體驗時，Mixed 和 Glass Arena 為遊戲加上沉浸光暈和房間選項。", "本格的な環境が欲しいときは、MixedとGlass Arenaがイマーシブなグローとルームを足します。")
    a("Wake your console, place the screen, and play. Version 1.3 adds ambient glow around the window in your space.", "Enciende la consola, coloca la pantalla y juega. La versión 1.3 añade resplandor ambiental alrededor de la ventana.", "Réveillez la console, placez l’écran et jouez. La version 1.3 ajoute une lueur ambiante autour de la fenêtre.", "Riattiva la console, posiziona lo schermo e gioca. La 1.3 aggiunge il bagliore ambientale intorno alla finestra.", "Ligue o console, posicione a tela e jogue. A versão 1.3 adiciona brilho ambiente ao redor da janela.", "Wecke die Konsole, platziere das Bild und spiele. Version 1.3 bringt Umgebungsleuchten um das Fenster.", "본체를 켜고 화면을 놓고 플레이하세요. 1.3은 창 둘레에 앰비언트 글로우를 더합니다.", "唤醒主机，放好画面，开始玩。1.3 为窗口周围加上环境光晕。", "喚醒主機，放好畫面，開始玩。1.3 為視窗周圍加上環境光暈。", "本体を起動し、画面を置いてプレイ。1.3はウィンドウ周りにアンビエントグローを追加します。")
    a("Plays the game's rumble, light bar colour, and DualSense trigger resistance on your controller.", "Reproduce la vibración, el color de la barra de luz y la resistencia de los gatillos DualSense en tu mando.", "Joue la vibration, la couleur de la barre lumineuse et la résistance des gâchettes DualSense.", "Riproduce vibrazione, colore della light bar e resistenza dei grilletti DualSense.", "Reproduz a vibração, a cor da light bar e a resistência dos gatilhos DualSense.", "Gibt Rumble, Light-Bar-Farbe und DualSense-Triggerwiderstand auf dem Controller wieder.", "게임의 진동, 라이트 바 색, DualSense 트리거 저항을 컨트롤러에 재생합니다.", "在手柄上播放游戏的震动、灯条颜色和 DualSense 扳机阻力。", "在手把上播放遊戲的震動、燈條顏色和 DualSense 扳機阻力。", "ゲームの振動、ライトバーの色、DualSenseのトリガー抵抗をコントローラーで再生します。")
    a("Holds a few frames so a busy Wi-Fi network does not stutter. Costs about 50 ms of input lag, and up to about 200 ms while the network is rough. Turn off for the fastest response.", "Guarda unos fotogramas para que una red Wi-Fi saturada no corte. Añade unos 50 ms de retraso, hasta unos 200 ms si la red va mal. Apágalo para la respuesta más rápida.", "Garde quelques images pour qu’un Wi-Fi chargé ne saccade pas. Environ 50 ms de latence, jusqu’à 200 ms si le réseau est mauvais. Désactivez pour la réponse la plus vive.", "Trattiene qualche fotogramma così una Wi-Fi piena non saltella. Circa 50 ms di ritardo, fino a 200 ms se la rete è brutta. Spegni per la risposta più rapida.", "Segura alguns quadros para uma Wi-Fi ocupada não travar. Custa uns 50 ms de atraso, até uns 200 ms se a rede estiver ruim. Desligue para a resposta mais rápida.", "Hält ein paar Frames, damit ein volles Wi-Fi nicht stockt. Etwa 50 ms Verzögerung, bis etwa 200 ms bei schlechtem Netz. Aus für die schnellste Reaktion.", "바쁜 Wi-Fi에서 끊기지 않도록 몇 프레임을 붙듭니다. 입력 지연이 약 50 ms, 네트워크가 나쁘면 최대 약 200 ms입니다. 가장 빠른 반응을 원하면 끄세요.", "多留几帧，避免忙碌的 Wi-Fi 卡顿。大约增加 50 毫秒延迟，网络差时最多约 200 毫秒。要最快手感就关掉。", "多留幾幀，避免忙碌的 Wi-Fi 卡頓。大約增加 50 毫秒延遲，網路差時最多約 200 毫秒。要最快手感就關掉。", "混雑したWi-Fiで途切れないよう数フレームを保持します。入力遅延は約50 ms、回線が悪いと最大約200 ms。最速の反応ならオフ。")
    a("The game keeps running while the headset is off, so you can put it back on and continue. After this long, Farframe ends the session the same way closing the player does: Rest PS5 if the toggle above is on, otherwise Disconnect.", "El juego sigue con el visor quitado; puedes volver a ponértelo. Pasado este tiempo, Farframe cierra la sesión igual que al cerrar el reproductor: reposo de PS5 si el interruptor de arriba está on, si no, desconexión.", "Le jeu continue casque retiré ; vous pouvez le remettre. Après ce délai, Farframe termine la session comme à la fermeture : repos PS5 si l’option ci-dessus est activée, sinon déconnexion.", "Il gioco continua a visore tolto; puoi rimetterlo. Dopo questo tempo Farframe chiude la sessione come alla chiusura: riposo PS5 se l’opzione sopra è attiva, altrimenti disconnessione.", "O jogo continua com o headset off; você pode colocar de novo. Depois deste tempo, o Farframe encerra a sessão como ao fechar: rest do PS5 se a opção acima estiver ligada, senão desconecta.", "Das Spiel läuft ohne Headset weiter. Nach dieser Zeit beendet Farframe die Sitzung wie beim Schließen: PS5-Ruhemodus wenn der Schalter oben an ist, sonst Trennen.", "헤드셋을 벗어도 게임은 계속됩니다. 이 시간이 지나면 Farframe이 플레이어를 닫을 때와 같이 세션을 끝냅니다. 위 스위치가 켜져 있으면 PS5 휴식, 아니면 연결 해제입니다.", "取下头显后游戏仍在运行，戴上即可继续。超过此时长后，Farframe 会像关闭播放器一样结束会话：上方开关打开则 PS5 休息模式，否则断开。", "取下頭戴裝置後遊戲仍在執行，戴上即可繼續。超過此時長後，Farframe 會像關閉播放器一樣結束工作階段：上方開關打開則 PS5 休息模式，否則中斷。", "ヘッドセットを外してもゲームは続きます。この時間を過ぎると、Farframeはプレイヤーを閉じたときと同じくセッションを終了します。上のスイッチがオンならPS5レスト、オフなら切断です。")

    legal = "Farframe is an independent application. It is not affiliated with, endorsed by, or sponsored by Sony Group Corporation, Sony Interactive Entertainment, PlayStation, PlayStation Network, or any of their affiliates. PlayStation, PS5, and PlayStation Network are trademarks or registered trademarks of their respective owners and are used only to describe compatibility with user-owned equipment."
    a(legal, legal, legal, legal, legal, legal, legal, legal, legal, legal)

    a("What's New in %@", "Novedades de %@", "Nouveautés de %@", "Novità di %@", "Novidades do %@", "Neuigkeiten in %@", "%@의 새로운 기능", "%@ 新功能", "%@ 新功能", "%@の新着情報")
    a("Version %@", "Versión %@", "Version %@", "Versione %@", "Versão %@", "Version %@", "버전 %@", "版本 %@", "版本 %@", "バージョン%@")
    a("Wake signal sent. Give %@ about ten seconds, then tap Connect.", "Señal enviada. Espera unos diez segundos a %@ y toca Conectar.", "Signal envoyé. Laissez environ dix secondes à %@, puis touchez Connexion.", "Segnale inviato. Dai a %@ circa dieci secondi, poi tocca Connetti.", "Sinal enviado. Dê uns dez segundos a %@ e toque em Conectar.", "Signal gesendet. Gib %@ etwa zehn Sekunden, dann Verbinden.", "신호를 보냈습니다. %@에 약 10초 기다린 뒤 연결을 탭하세요.", "已发送唤醒。给 %@ 大约十秒，然后点连接。", "已傳送喚醒。給 %@ 大約十秒，然後點連接。", "起動信号を送りました。%@を約10秒待ってから接続をタップします。")
    a("%@ is paired", "%@ está vinculada", "%@ est associée", "%@ è associata", "%@ está vinculado", "%@ ist gekoppelt", "%@이(가) 연결됨", "%@ 已配对", "%@ 已配對", "%@を登録済み")
    a("More options for %@", "Más opciones para %@", "Plus d’options pour %@", "Altre opzioni per %@", "Mais opções para %@", "Weitere Optionen für %@", "%@ 옵션 더 보기", "%@ 的更多选项", "%@ 的更多選項", "%@のその他のオプション")
    a("%@ for Apple Vision Pro", "%@ para Apple Vision Pro", "%@ pour Apple Vision Pro", "%@ per Apple Vision Pro", "%@ para Apple Vision Pro", "%@ für Apple Vision Pro", "Apple Vision Pro용 %@", "适用于 Apple Vision Pro 的 %@", "適用於 Apple Vision Pro 的 %@", "Apple Vision Pro向け%@")
    a("Remove %@", "Eliminar %@", "Supprimer %@", "Rimuovi %@", "Remover %@", "%@ entfernen", "%@ 삭제", "移除 %@", "移除 %@", "%@を削除")
    a("Decrease %@", "Reducir %@", "Diminuer %@", "Riduci %@", "Diminuir %@", "%@ verringern", "%@ 줄이기", "减小 %@", "減小 %@", "%@を下げる")
    a("Increase %@", "Aumentar %@", "Augmenter %@", "Aumenta %@", "Aumentar %@", "%@ erhöhen", "%@ 늘리기", "增大 %@", "增大 %@", "%@を上げる")
    a("%lld%%", "%lld %%", "%lld %%", "%lld%%", "%lld%%", "%lld %%", "%lld%%", "%lld%%", "%lld%%", "%lld%%")
    a("FARFRAME", "FARFRAME", "FARFRAME", "FARFRAME", "FARFRAME", "FARFRAME", "FARFRAME", "FARFRAME", "FARFRAME", "FARFRAME")
    a("The easiest way is to tap Continue with PlayStation on the pairing screen and sign in. Farframe reads your Remote Play Account ID from that sign-in and keeps only the ID. You never need to type it.",
      "Lo más fácil es tocar Continuar con PlayStation en la pantalla de vínculo e iniciar sesión. Farframe lee el Account ID de Remote Play y solo guarda el ID. No hace falta escribirlo.",
      "Le plus simple est de toucher Continuer avec PlayStation à l’association et de vous connecter. Farframe lit l’Account ID Remote Play et ne garde que l’ID. Pas besoin de le saisir.",
      "Il modo più semplice è toccare Continua con PlayStation e accedere. Farframe legge l’Account ID di Remote Play e tiene solo l’ID. Non devi digitarlo.",
      "O mais fácil é tocar em Continuar com PlayStation na tela de vínculo e entrar. O Farframe lê o Account ID do Remote Play e guarda só o ID. Você não precisa digitá-lo.",
      "Am einfachsten: Auf dem Kopplungsbildschirm Mit PlayStation fortfahren und anmelden. Farframe liest die Remote-Play-Account-ID und behält nur die ID. Tippen entfällt.",
      "가장 쉬운 방법은 연결 화면에서 PlayStation으로 계속을 탭하고 로그인하는 것입니다. Farframe이 Remote Play Account ID만 읽고 저장합니다. 직접 입력할 필요는 없습니다.",
      "最简单的是在配对屏幕点使用 PlayStation 继续并登录。Farframe 只读取并保存 Remote Play Account ID。不必手打。",
      "最簡單的是在配對畫面點使用 PlayStation 繼續並登入。Farframe 只讀取並儲存 Remote Play Account ID。不必手打。",
      "いちばん簡単なのは、登録画面でPlayStationで続けるをタップしてサインインすることです。FarframeはRemote Play Account IDだけを読み取り、保存します。手入力は不要です。")
    a("If you already have this value from an earlier Remote Play setup, paste it in the Advanced field. Farframe accepts the numeric, base64, and 16-character hexadecimal forms.",
      "Si ya lo tienes de otro Remote Play, pégalo en Avanzado. Farframe acepta formas numéricas, base64 y hexadecimal de 16 caracteres.",
      "Si vous l’avez déjà d’un autre Remote Play, collez-le dans Avancé. Farframe accepte les formes numérique, base64 et hexadécimale sur 16 caractères.",
      "Se ce l’hai già da un altro Remote Play, incollalo in Avanzate. Farframe accetta forme numeriche, base64 e esadecimali a 16 caratteri.",
      "Se você já tem de outro Remote Play, cole em Avançado. O Farframe aceita formas numérica, base64 e hexadecimal de 16 caracteres.",
      "Wenn du den Wert schon von einem anderen Remote Play hast, in Erweitert einfügen. Farframe nimmt Zahl, Base64 und 16-stelliges Hex an.",
      "이미 다른 Remote Play에서 이 값이 있으면 고급 필드에 붙여 넣으세요. Farframe은 숫자, base64, 16자 16진 형식을 받습니다.",
      "若你从以前的 Remote Play 已有此值，请粘贴到高级栏。Farframe 接受数字、base64 和 16 位十六进制。",
      "若你從以前的 Remote Play 已有此值，請貼到進階欄。Farframe 接受數字、base64 和 16 位十六進位。",
      "以前のRemote Playでこの値がある場合は、詳細欄に貼り付けます。Farframeは数値、base64、16文字の16進を受け付けます。")
    a("It is a 64-bit number tied to your PlayStation account. It is not your Online ID, your email address, or your password.",
      "Es un número de 64 bits de tu cuenta PlayStation. No es el Online ID, el correo ni la contraseña.",
      "C’est un nombre 64 bits lié au compte PlayStation. Ce n’est pas l’Online ID, l’e-mail ni le mot de passe.",
      "È un numero a 64 bit legato all’account PlayStation. Non è l’Online ID, l’email o la password.",
      "É um número de 64 bits da conta PlayStation. Não é o Online ID, o e-mail nem a senha.",
      "Es ist eine 64-Bit-Zahl zu deinem PlayStation-Konto. Nicht Online ID, E-Mail oder Passwort.",
      "PlayStation 계정에 묶인 64비트 숫자입니다. Online ID, 이메일, 비밀번호가 아닙니다.",
      "这是绑定 PlayStation 帐户的 64 位数字。不是 Online ID、邮箱或密码。",
      "這是綁定 PlayStation 帳號的 64 位數字。不是 Online ID、電子郵件或密碼。",
      "PlayStationアカウントに紐づく64ビットの数値です。Online ID、メール、パスワードではありません。")
    a("Enter your password and two-factor code only on Sony’s sign-in page. Never paste them, cookies, or access tokens into the manual Account ID field.",
      "La contraseña y el código de dos factores, solo en la página de Sony. Nunca los pegues, ni cookies ni tokens, en el campo manual de Account ID.",
      "Mot de passe et code à deux facteurs uniquement sur la page Sony. Ne les collez jamais, ni cookies ni jetons, dans le champ Account ID manuel.",
      "Password e codice a due fattori solo sulla pagina Sony. Non incollarli, né cookie né token, nel campo Account ID manuale.",
      "Senha e código de dois fatores só na página da Sony. Nunca cole, nem cookies nem tokens, no campo manual de Account ID.",
      "Passwort und Zwei-Faktor-Code nur auf Sonys Anmeldeseite. Niemals in das manuelle Account-ID-Feld, auch keine Cookies oder Tokens.",
      "비밀번호와 2단계 코드는 Sony 로그인 페이지에서만 입력하세요. 수동 Account ID 칸에 붙여 넣거나 쿠키·토큰을 넣지 마세요.",
      "密码和两步验证码只在 Sony 登录页输入。切勿粘贴到手动 Account ID 栏，也不要放 cookie 或令牌。",
      "密碼和兩步驟驗證碼只在 Sony 登入頁輸入。切勿貼到手動 Account ID 欄，也不要放 cookie 或權杖。",
      "パスワードと二要素コードはSonyのサインインページだけで入力します。手動のAccount ID欄に貼ったり、Cookieやトークンを入れたりしないでください。")
    a("Farframe keeps the Account ID and Link Device code only for the pairing attempt. The saved console registration lives in this device's Keychain and is not synchronized anywhere.",
      "Farframe guarda el Account ID y el código Link Device solo durante el intento de vínculo. El registro de la consola vive en el Keychain de este dispositivo y no se sincroniza.",
      "Farframe conserve l’Account ID et le code Link Device seulement pour la tentative d’association. L’enregistrement de la console est dans le Keychain de cet appareil et n’est synchronisé nulle part.",
      "Farframe tiene Account ID e codice Link Device solo per il tentativo di associazione. La registrazione della console sta nel Keychain di questo dispositivo e non si sincronizza.",
      "O Farframe guarda o Account ID e o código Link Device só na tentativa de vínculo. O registro do console fica no Keychain deste dispositivo e não sincroniza.",
      "Farframe behält Account ID und Link-Device-Code nur für den Kopplungsversuch. Die Konsolenregistrierung liegt in der Keychain dieses Geräts und wird nirgends synchronisiert.",
      "Farframe은 연결 시도 동안에만 Account ID와 Link Device 코드를 보관합니다. 본체 등록은 이 기기의 Keychain에 있으며 어디에도 동기화되지 않습니다.",
      "Farframe 仅在本次配对尝试中保留 Account ID 和 Link Device 代码。主机注册存在此设备的 Keychain 中，不会同步到别处。",
      "Farframe 僅在本次配對嘗試中保留 Account ID 和 Link Device 代碼。主機註冊存在此裝置的 Keychain 中，不會同步到別處。",
      "Farframeは登録の試行中だけAccount IDとLink Deviceコードを保持します。本体の登録はこのデバイスのKeychainにあり、どこにも同期しません。")
    a("Sony blocks PS Plus cloud-streamed games from Remote Play video. Download the game to this PS5, then launch the installed copy to play it here.",
      "Sony bloquea el vídeo de Remote Play en juegos en la nube de PS Plus. Descarga el juego en esta PS5 y ábrelo instalado para jugarlo aquí.",
      "Sony bloque la vidéo Remote Play des jeux cloud PS Plus. Téléchargez le jeu sur cette PS5, puis lancez la copie installée.",
      "Sony blocca il video Remote Play dei giochi cloud PS Plus. Scarica il gioco su questa PS5 e avvia la copia installata.",
      "A Sony bloqueia o vídeo de Remote Play em jogos na nuvem do PS Plus. Baixe o jogo neste PS5 e abra a cópia instalada.",
      "Sony sperrt Remote-Play-Video bei PS-Plus-Cloudspielen. Das Spiel auf diese PS5 laden und die installierte Kopie starten.",
      "Sony는 PS Plus 클라우드 게임의 Remote Play 영상을 막습니다. 이 PS5에 게임을 받은 뒤 설치된 사본을 실행하세요.",
      "Sony 会拦截 PS Plus 云游戏的 Remote Play 画面。请把游戏下载到这台 PS5，再启动安装版。",
      "Sony 會攔截 PS Plus 雲遊戲的 Remote Play 畫面。請把遊戲下載到這台 PS5，再啟動安裝版。",
      "SonyはPS PlusクラウドゲームのRemote Play映像をブロックします。このPS5にゲームをダウンロードし、インストール版を起動してください。")
    a("Option 1: use the button below to send PS, D-pad down, then Cross and return to PlayStation Home.",
      "Opción 1: usa el botón de abajo para enviar PS, cruceta abajo y Cross, y volver a PlayStation Home.",
      "Option 1 : utilisez le bouton ci-dessous pour envoyer PS, croix bas, puis Cross, et revenir à PlayStation Home.",
      "Opzione 1: usa il pulsante sotto per inviare PS, D-pad giù, poi Cross e tornare a PlayStation Home.",
      "Opção 1: use o botão abaixo para enviar PS, direcional para baixo e Cross, e voltar à PlayStation Home.",
      "Option 1: Mit der Taste unten PS, Steuerkreuz runter, dann Cross senden und zu PlayStation Home.",
      "옵션 1: 아래 버튼으로 PS, 십자 아래, Cross를 보낸 뒤 PlayStation Home으로 돌아갑니다.",
      "选项 1：用下面的按钮发送 PS、方向键下、然后 Cross，回到 PlayStation Home。",
      "選項 1：用下面的按鈕傳送 PS、方向鍵下、然後 Cross，回到 PlayStation Home。",
      "オプション1: 下のボタンでPS、十字下、Crossを送り、PlayStation Homeに戻ります。")
    a("Manual: press the in-app PS button, press D-pad down once, then press Cross.",
      "Manual: pulsa el botón PS de la app, cruceta abajo una vez y luego Cross.",
      "Manuel : bouton PS dans l’app, croix bas une fois, puis Cross.",
      "Manuale: premi PS nell’app, D-pad giù una volta, poi Cross.",
      "Manual: pressione PS no app, direcional para baixo uma vez e depois Cross.",
      "Manuell: PS-Taste in der App, einmal Steuerkreuz runter, dann Cross.",
      "수동: 앱의 PS 버튼, 십자 아래 한 번, 그다음 Cross.",
      "手动：按 App 内 PS，方向键下一次，再按 Cross。",
      "手動：按 App 內 PS，方向鍵下一次，再按 Cross。",
      "手動: App内のPS、十字下を一度、それからCross。")
    a("Fallback: if the console is stuck on the PS Plus prompt, disconnect, wake/relaunch Remote Play, then open an installed game.",
      "Reserva: si la consola se queda en el aviso de PS Plus, desconecta, activa o relanza Remote Play y abre un juego instalado.",
      "Secours : si la console reste sur l’invite PS Plus, déconnectez, réveillez ou relancez Remote Play, puis ouvrez un jeu installé.",
      "Riserva: se la console resta sul prompt PS Plus, disconnetti, riattiva o rilancia Remote Play, poi apri un gioco installato.",
      "Reserva: se o console travar no aviso de PS Plus, desconecte, ligue ou reabra o Remote Play e abra um jogo instalado.",
      "Ausweg: Hängt die Konsole am PS-Plus-Hinweis, trennen, Remote Play wecken/neu starten, installiertes Spiel öffnen.",
      "대안: 본체가 PS Plus 화면에 멈추면 연결을 끊고 Remote Play를 켜거나 다시 연 뒤, 설치된 게임을 여세요.",
      "备用：若主机停在 PS Plus 提示，请断开，唤醒或重开 Remote Play，然后打开已安装的游戏。",
      "備用：若主機停在 PS Plus 提示，請中斷，喚醒或重開 Remote Play，然後打開已安裝的遊戲。",
      "予備: 本体がPS Plusの画面で止まったら切断し、Remote Playを起動し直して、インストール済みゲームを開きます。")
    a("Connect this device and your console to the same home network. This version supports home-network play.",
      "Conecta este dispositivo y la consola a la misma red de casa. Esta versión admite juego en red local.",
      "Mettez cet appareil et la console sur le même réseau local. Cette version prend en charge le jeu à la maison.",
      "Collega questo dispositivo e la console alla stessa rete di casa. Questa versione supporta il gioco in rete locale.",
      "Coloque este dispositivo e o console na mesma rede de casa. Esta versão é para jogo na rede local.",
      "Dieses Gerät und die Konsole ins selbe Heimnetz. Diese Version unterstützt Heimnetz-Spiel.",
      "이 기기와 본체를 같은 집 네트워크에 두세요. 이 버전은 집 네트워크 플레이를 지원합니다.",
      "让此设备与主机加入同一家庭网络。此版本支持家庭网络游玩。",
      "讓此裝置與主機加入同一家庭網路。此版本支援家庭網路遊玩。",
      "このデバイスと本体を同じ自宅ネットワークにしてください。このバージョンは自宅ネットワークプレイに対応します。")
    a("On PS5, open Settings > System > Remote Play > Link Device and leave the eight-digit code on screen.",
      "En PS5, Ajustes > Sistema > Remote Play > Link Device y deja el código de ocho dígitos en pantalla.",
      "Sur PS5, Réglages > Système > Remote Play > Link Device et laissez le code à huit chiffres à l’écran.",
      "Su PS5, Impostazioni > Sistema > Remote Play > Link Device e lascia il codice a otto cifre sullo schermo.",
      "No PS5, Ajustes > Sistema > Remote Play > Link Device e deixe o código de oito dígitos na tela.",
      "Auf der PS5: Einstellungen > System > Remote Play > Link Device, achtstelligen Code auf dem Bildschirm lassen.",
      "PS5에서 설정 > 시스템 > Remote Play > Link Device를 열고 8자리 코드를 화면에 두세요.",
      "在 PS5 打开设置 > 系统 > Remote Play > Link Device，让八位代码留在屏幕上。",
      "在 PS5 打開設定 > 系統 > Remote Play > Link Device，讓八位代碼留在畫面上。",
      "PS5で設定 > システム > Remote Play > Link Deviceを開き、8桁コードを画面に出したままにします。")
    a("Enter the code in Farframe and tap Pair. The code expires in a few minutes, so request a fresh one if it fails.",
      "Introduce el código en Farframe y toca Vincular. Caduca en unos minutos; pide uno nuevo si falla.",
      "Saisissez le code dans Farframe et touchez Associer. Il expire en quelques minutes ; demandez-en un nouveau en cas d’échec.",
      "Inserisci il codice in Farframe e tocca Associa. Scade in pochi minuti; richiedine uno nuovo se fallisce.",
      "Digite o código no Farframe e toque em Vincular. Expira em poucos minutos; peça outro se falhar.",
      "Code in Farframe eingeben und Koppeln. Er läuft in wenigen Minuten ab; bei Fehler einen neuen holen.",
      "Farframe에 코드를 입력하고 연결을 탭하세요. 몇 분이면 만료되니 실패하면 새 코드를 받으세요.",
      "在 Farframe 输入代码并点配对。代码几分钟后过期，失败就申请新的。",
      "在 Farframe 輸入代碼並點配對。代碼幾分鐘後過期，失敗就申請新的。",
      "Farframeにコードを入力して登録をタップします。数分で期限切れなので、失敗したら新しいコードを発行します。")
    a("Farframe needs local network access to find and connect to your PlayStation 5.",
      "Farframe necesita acceso a la red local para encontrar y conectar tu PlayStation 5.",
      "Farframe a besoin du réseau local pour trouver et connecter votre PlayStation 5.",
      "Farframe richiede la rete locale per trovare e connettere la PlayStation 5.",
      "O Farframe precisa da rede local para encontrar e conectar o PlayStation 5.",
      "Farframe braucht lokales Netz, um deine PlayStation 5 zu finden und zu verbinden.",
      "Farframe이 PlayStation 5를 찾고 연결하려면 로컬 네트워크 접근이 필요합니다.",
      "Farframe 需要本地网络权限才能查找并连接你的 PlayStation 5。",
      "Farframe 需要本機網路權限才能尋找並連接你的 PlayStation 5。",
      "FarframeがPlayStation 5を見つけて接続するには、ローカルネットワークへのアクセスが必要です。")
    return t
