if(NOT DEFINED RP_SYSTEM_NAME)
    message(FATAL_ERROR "RP_SYSTEM_NAME is required")
endif()
if(NOT DEFINED RP_SDK)
    message(FATAL_ERROR "RP_SDK is required")
endif()
if(NOT DEFINED RP_ARCH)
    message(FATAL_ERROR "RP_ARCH is required")
endif()
if(NOT DEFINED RP_MIN_OS)
    message(FATAL_ERROR "RP_MIN_OS is required")
endif()
if(NOT DEFINED RP_TARGET_TRIPLE)
    message(FATAL_ERROR "RP_TARGET_TRIPLE is required")
endif()

set(
    CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    RP_SYSTEM_NAME
    RP_SDK
    RP_ARCH
    RP_MIN_OS
    RP_TARGET_TRIPLE
)

set(CMAKE_SYSTEM_NAME "${RP_SYSTEM_NAME}")
set(CMAKE_SYSTEM_PROCESSOR "${RP_ARCH}")
set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)

execute_process(
    COMMAND xcrun --sdk "${RP_SDK}" --show-sdk-path
    OUTPUT_VARIABLE RP_SDK_PATH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY
)
execute_process(
    COMMAND xcrun --sdk "${RP_SDK}" --find clang
    OUTPUT_VARIABLE RP_CLANG
    OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY
)
execute_process(
    COMMAND xcrun --sdk "${RP_SDK}" --find clang++
    OUTPUT_VARIABLE RP_CLANGXX
    OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY
)

set(CMAKE_OSX_SYSROOT "${RP_SDK_PATH}" CACHE PATH "" FORCE)
set(CMAKE_OSX_ARCHITECTURES "${RP_ARCH}" CACHE STRING "" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET "${RP_MIN_OS}" CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER "${RP_CLANG}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${RP_CLANGXX}" CACHE FILEPATH "" FORCE)
set(CMAKE_C_COMPILER_TARGET "${RP_TARGET_TRIPLE}" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_TARGET "${RP_TARGET_TRIPLE}" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
